name: Update Latest Release

on:
  push:
    branches:
      - main

jobs:
  update-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create or Update "latest" Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          body: |
            Automatic release on daily anycast census push.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
